### ISSUE TITLE
Use correct symfony cache folder for temp_dir

### ISSUE THREAD

**Issue by alexander-schranz** [Padam87/RasterizeBundle#12]
Default config should be something like:

```yml
padam87_rasterize:
    temp_dir: %kernel.cache_dir%/padam87_rasterize
```

this dont work because it will prefix this path with root dir.

**Comment by Padam87** [comment]
Unfortunately the temp dir has to be accessible, so the rasterizer script can load the address. The cache dir would be appropriate, however it is not accessible from the web.

**Comment by alexander-schranz** [comment]
you should create a controller which does a `BinaryFileResponse` of the cache file. Not every hoster give you the access to write into the public path.

**Comment by Padam87** [comment]
If this was a bundle with 200+ stars, and 100+ consistent users, I perhaps would :)
There is nothing preventing individual developers from doing so, so I'm fine with it.
