### ISSUE TITLE
Pdf always empty

### ISSUE THREAD

**Issue by benjaminb-** [Padam87/RasterizeBundle#16]
Hello, i used this bundle 2 year ago with phantomjs (and temp files, version 1.x) and it was working well. Thanks to the author ;)

I use it now in a new project with the last version and puppeteer.

But it's not working for me, the PDF is always empty.

The process output is empty, i tried to pass a simple string (not a twig render) in the rasterize method and it's not working too.

Maybe i'm doing something wrong ? I can provide informations if needed, i don't know what to do to precise the bug.

Thanks !!

**Comment by Padam87** [comment]
Hi,

I use this bundle in multiple projects, and the most recent version works well too. Are you still using it with phantomjs, or have you switched to puppeteer?

Could you post your rasterizer script?

Thanks,
Adam

**Comment by benjaminb-** [comment]
Hey thanks for your time :)

For debugging it tried to get the content from the script in the rasterize method 

````
$process = $this->configHelper->buildProcess($input, $arguments);
        $process->start(null, []);

       // html is containing the content..

        $input->write($html);
        $input->close();

        $process->wait();

        if ($this->stopwatch instanceof Stopwatch) {
            $this->stopwatch->stop('rasterizer');
        }


 // the process output is an empty string
        return $process->getOutput();
````

I'm using puppeteer.

```
const puppeteer = require('puppeteer');
const fs = require('fs');

let stdinBuffer = fs.readFileSync(0 /* STDIN_FILENO */, 'utf8');
let html = stdinBuffer.toString();

const args = process.argv;
const format = args[2];

(async () => {
    const browser = await puppeteer.launch({
        ignoreHTTPSErrors: true
    });
    const page = await browser.newPage();

    // https://github.com/GoogleChrome/puppeteer/issues/728
    // await page.setContent(html);
    // await page.waitForNavigation({ waitUntil: 'networkidle0' });

    await page.goto('data:text/html,' + html, { waitUntil: 'networkidle0' });

    if (format == 'pdf') {
        await page.pdf({
            path: 1, // STDOUT_FILENO
            format: 'A4',
            printBackground: true,
            margin: { top: '1cm', right: '1cm', bottom: '1cm', left: '1cm' }
        });
    } else {
        await page.screenshot({
            path: 1, // STDOUT_FILENO
            type: format,
            quality: 100,
        });
    }
    await browser.close();
})(); 
```

It's the file provided.

Is there any way to debug in the javascript side ?

**Comment by benjaminb-** [comment]
I just tried

```
dump($process->getErrorOutput());
```

and yes i have an error 

(node:389) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): AssertionError: Chromium revision is not downloaded. Run "npm install" or "yarn install

**Comment by Padam87** [comment]
/etc/yum.repos.d/google-chrome.repo
```
[google-chrome]
name=google-chrome
baseurl=http://dl.google.com/linux/chrome/rpm/stable/x86_64
enabled=1
gpgcheck=1
gpgkey=https://dl.google.com/linux/linux_signing_key.pub
```

dnf install chromedriver
dnf install google-chrome-stable

**Comment by benjaminb-** [comment]
Thanks, i have an another error now 

````
(node:77) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!\n
[0424/133521.639995:FATAL:zygote_host_impl_linux.cc(124)] No usable sandbox! 
````

it's not from your great lib, i'll fix that ! thanks for your time and your work :) !!

**Comment by Padam87** [comment]
Thank you! I'm adding some test/debug instructions to the docs, as I think this problem will be quite common.

**Comment by Padam87** [comment]
Haven't seen this one unfortunately. I will try an upgrade later today, maybe something with a newer version?

**Comment by benjaminb-** [comment]
Which puppeteer version do you have ? 

I'm working in a docker environment also it could be an issue with puppeteer

**Comment by Padam87** [comment]
Upgraded to 1.3, still fine. Tested it on fedora and windows. I use LXC, not docker, so I cannot test it there.

Node versions tested: v8.10.0, v9.4.0

**Comment by Padam87** [comment]
Thank you very much! I will link the issue so others may find it: https://github.com/GoogleChrome/puppeteer/issues/2454

I will update the example config, as this looks like a less painful way to do it :)
