### ISSUE TITLE
NODE_PATH for global puppeteer

### ISSUE THREAD

**Issue by markitosgv** [Padam87/RasterizeBundle#17]
Hi,

First of all, nice bundle!

I've got a problem, I want to use puppeteer as a global node dependency, for my goal I need to set NODE_PATH as environment variable for Symfony process in Rasterize.php

After line 27 in Rasterizer.php:
```php
        $process->setEnv([
            'NODE_PATH' => '/usr/local/lib/node_modules',
        ]);
```

Do you think it's possible to extend your bundle for passing environment variables to the process?

**Comment by Padam87** [comment]
Hi,

Thank you. I have added env_vars as a configuration option, and a callback after the process creation.

See https://github.com/Padam87/RasterizeBundle/pull/18
