### ISSUE TITLE
PhantomJS  config missing from repository

### ISSUE THREAD

**Issue by Epskampie** [Padam87/RasterizeBundle#19]
Nice bundle, thanks for making it!

The phantomjs documentation seems to be missing though. This link, mentioned in README.md is dead: https://github.com/Padam87/RasterizeBundle/blob/master/Resources/docs/provider/phantomjs.md

**Comment by Padam87** [comment]
Hi @Epskampie ,

Thanks for the notifying me, seems like I forgot to copy it from v2.

Check this if you need it ASAP:
https://github.com/Padam87/RasterizeBundle/blob/2.x/Resources/public/js/rasterize.js

I will do a test and write the docs once I finished my current task.

**Comment by Padam87** [comment]
Given phantomjs's current state I'm not sure I should encourage using it. It was stalled for a long time, and not it is officially dead.

v2 had a lot of issues....

I strongly encourage using puppeteer at this point.

**Comment by Epskampie** [comment]
I agree, I'm using puppeteer already and it is AWESOME! you might just want to take the references to phantomjs out of the README and the repository headline: 

> HTML to PDF Symfony bundle. Works with Puppeteer, PhantomJS, and more.

**Comment by Padam87** [comment]
Yep. I think I will just add the "other" part. The basics are the same everywhere. HTML in, PDF out.

Thanks!
