### ISSUE TITLE
Bug? or something else in the bundle

### ISSUE THREAD

**Issue by nelp** [Padam87/RasterizeBundle#5]
HI.
I use this bundle on a site with https. In my config I have set these options
            --ssl-protocol: tlsv1
            --ssl-certificates-path: /path/to/certificate/
            --ignore-ssl-errors: true

When I try to get the pdf I get an error "ContextErrorException: Warning: file_get_contents..."
When I in the bundles ConfigHelper.php change line 220 from 
                $options[] = sprintf('%s="%s"', $name, $value);
to
                $options[] = sprintf('%s=%s', $name, $value); 
without the quotes on %s it works as expected.

For me it looks like an error in the bundle but maybe I am missing something.
Thanks for your help.

**Comment by Padam87** [comment]
Hi,

Escaping seems to cause problems in the symfony process builder. Could you create a PR (with a failing tests) removing this?

Thanks!
